n1 = input('Digite algo: ')
print('O tipo primitivo é {}'.format(type(n1)))
print('só tem espaços? {}'.format(n1.isspace()))
print('é um número? {}'.format(n1.isnumeric()))
print('é alfabético? {}'.format(n1.isalpha()))
print('é alfanumérico? {}'.format(n1.isalnum()))
print('está em maiúsculas? {}'.format(n1.isupper()))
print('está em minúsculas? {}'.format(n1.islower()))
print('está capitalizada? {}'.format(n1.istitle()))